const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Physics,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Plugins.Tilemap,
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.bound,
		C3.Behaviors.EightDir,
		C3.Plugins.Keyboard,
		C3.Behaviors.Rotate,
		C3.Behaviors.LOS,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.DrawingCanvas.Acts.SetSize,
		C3.Plugins.DrawingCanvas.Acts.SetResolutionMode,
		C3.Plugins.DrawingCanvas.Exps.Width,
		C3.Plugins.DrawingCanvas.Exps.Height,
		C3.Plugins.DrawingCanvas.Acts.SetPos,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.DrawingCanvas.Acts.SaveSnapshot,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.DrawingCanvas.Acts.Destroy,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.DrawingCanvas.Cnds.OnSnapshot,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.DrawingCanvas.Exps.SurfaceDeviceHeight,
		C3.Plugins.DrawingCanvas.Exps.SurfaceDeviceWidth,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.DrawingCanvas.Exps.SnapshotAlphaAt,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.DrawingCanvas.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.Y,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.DrawingCanvas.Exps.SnapshotRedAt,
		C3.Plugins.DrawingCanvas.Exps.SnapshotBlueAt,
		C3.Plugins.DrawingCanvas.Exps.SnapshotGreenAt,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.System.Exps.layertocanvasx,
		C3.Plugins.System.Exps.layertocanvasy,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.SetVolume,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{DragDrop: 0},
	{Physics: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Sine: 0},
	{Sine2: 0},
	{Слой: 0},
	{Tilemap: 0},
	{DrawingCanvas: 0},
	{BoundToLayout: 0},
	{"8Direction": 0},
	{Camera: 0},
	{MiniBlock: 0},
	{Keyboard: 0},
	{oldX: 0},
	{oldY: 0},
	{Rotate: 0},
	{LineOfSight: 0},
	{Pila: 0},
	{Touch: 0},
	{TouchScrol: 0},
	{LeftHend: 0},
	{RightHend: 0},
	{Body: 0},
	{LeftLeg: 0},
	{Head: 0},
	{RightLeg: 0},
	{Spawn: 0},
	{Audio: 0},
	{Video: 0},
	{Video2: 0},
	{BlockSize: 0},
	{PixelRed: 0},
	{PixelGreen: 0},
	{PixelBlue: 0},
	{PixelAlpha: 0},
	{TapLockX: 0},
	{TapLockY: 0},
	{TapLockX2: 0},
	{TapLockY2: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Слой: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	Camera: class extends self.ISpriteInstance {},
	MiniBlock: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Pila: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	TouchScrol: class extends self.ISpriteInstance {},
	LeftHend: class extends self.ISpriteInstance {},
	RightHend: class extends self.ISpriteInstance {},
	Body: class extends self.ISpriteInstance {},
	LeftLeg: class extends self.ISpriteInstance {},
	Head: class extends self.ISpriteInstance {},
	RightLeg: class extends self.ISpriteInstance {},
	Spawn: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Video: class extends self.IWorldInstance {},
	Video2: class extends self.IWorldInstance {}
}